### ISSUE TITLE
Add logic to track pipeline information in CoreGenSigMap

### ISSUE THREAD

**Issue by jleidel** [opensocsysarch/CoreGen#263]
This should include syntax to define the pipelines, their attributes and the associated stages
```
- Pipelines
  - Pipeline: FOO
    Attributes:
      - Attribute: BAR1
      - Attribute: BAR2
    Stages:
      - Stage: FOOBAR1
      - Stage: FOOBAR2
```
