### ISSUE TITLE
Add VLIWStage Nodes to CoreGen YAML IR

### ISSUE THREAD

**Issue by jleidel** [opensocsysarch/CoreGen#370]
This will require an entirely new node type in order to represent the VLIWStages.  Something similar to the following: 

```
VLIWStages
  - VLIWStageName: Name
    InstFormat: format
    Inputs:
      - in0
      - in1
    Ouputs:
       - out0
       - out1
```
